version: '3.7'

services:
  app:
    container_name: abinetpp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
